openapi: 3.0.4
info:
  description: Hackz Hackathon Brachio CUP のAPI仕様書。
  title: Hackz Hackathon Brachio CUP API Spec
  version: 0.0.1
servers:
- description: ローカルサーバー
  url: http://localhost:8080
tags:
- description: ガチャに関するAPI
  name: gacha
paths:
  /users/{userId}:
    get:
      description: Get user by user ID
      operationId: getUser
      parameters:
      - description: ID of user to return
        in: path
        name: userId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: successful operation
      summary: Get user by user ID
      tags:
      - user
  /gachas:
    get:
      description: ガチャ一覧を取得する
      operationId: getGachaList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/gacha'
                type: array
          description: OK
      summary: ガチャ一覧取得
      tags:
      - gacha
  /gachas/power:
    get:
      description: ガチャの強さを取得する
      operationId: getGachaPower
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gachaPower'
          description: OK
      summary: ガチャの強さ取得
      tags:
      - gacha
  /gachas/{gachaId}:
    post:
      description: ガチャを引く
      operationId: drawGacha
      parameters:
      - description: ガチャID
        in: path
        name: gachaId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/drawGachaRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/pack'
                type: array
          description: OK
      summary: ガチャを引く
      tags:
      - gacha
  /items:
    get:
      description: 所持アイテム一覧を取得します。
      operationId: getMyItemList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/item'
                type: array
          description: アイテム一覧
      summary: 所持アイテム一覧取得
      tags:
      - item
  /decks:
    get:
      description: 自身のデッキリストを取得する
      operationId: getDeckList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/deckBaseWithId'
                type: array
          description: OK
      summary: 自身のデッキリストを取得
      tags:
      - deck
    post:
      description: 空のデッキを作成する
      operationId: createNewDeck
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createNewDeck_201_response'
          description: Created
      summary: 空のデッキを作成
      tags:
      - deck
  /decks/{deckId}:
    delete:
      description: デッキを削除する
      operationId: deleteDeck
      parameters:
      - description: デッキID
        in: path
        name: deckId
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
      summary: デッキを削除
      tags:
      - deck
    get:
      description: デッキを取得する
      operationId: getDeck
      parameters:
      - description: デッキID
        in: path
        name: deckId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deckWithId'
          description: OK
      summary: デッキを取得
      tags:
      - deck
    put:
      description: デッキを更新する
      operationId: updateDeck
      parameters:
      - description: デッキID
        in: path
        name: deckId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDeck'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deckWithId'
          description: OK
      summary: デッキを更新
      tags:
      - deck
  /cards:
    get:
      description: 取得済みカード一覧を取得する
      operationId: getCards
      parameters:
      - description: "全件取得フラグ（0: 非全件, 1: 全件)"
        in: query
        name: is_all
        required: false
        schema:
          enum:
          - 0
          - 1
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/myCardList'
          description: OK
      summary: 取得済みカード一覧の取得
      tags:
      - card
  /presents:
    get:
      description: プレゼント一覧を取得する
      operationId: getMyPresents
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/present'
                type: array
          description: プレゼント一覧
      summary: プレゼント一覧取得
      tags:
      - present
  /presents/{presentId}:
    post:
      description: プレゼントを受け取る
      operationId: receivePresent
      parameters:
      - description: プレゼントID
        in: path
        name: presentId
        required: true
        schema:
          type: string
      responses:
        "204":
          description: 受け取り成功
      summary: プレゼント受け取り
      tags:
      - present
  /ws:
    get:
      operationId: ws
      responses:
        "200":
          description: OK
      summary: Websocket接続
  /:
    get:
      operationId: healthCheck
      responses:
        "200":
          description: OK
      summary: health check
components:
  schemas:
    user:
      example:
        imageUrl: imageUrl
        name: name
      properties:
        name:
          description: ユーザー名
          type: string
        imageUrl:
          description: 画像URL
          type: string
      required:
      - imageUrl
      - name
      type: object
    gacha:
      example:
        imageUrl: imageUrl
        name: name
        id: id
      properties:
        id:
          description: ガチャID
          readOnly: true
          type: string
        name:
          description: ガチャ名
          type: string
        imageUrl:
          description: ガチャ画像URL
          type: string
      required:
      - id
      - imageUrl
      - name
      type: object
    gachaPower:
      example:
        next: 0
        charged: 6
      properties:
        next:
          description: 次のガチャパワーが貯まるまでの秒数
          type: integer
        charged:
          description: 現在のガチャパワー
          type: integer
      required:
      - charged
      - next
      type: object
    drawGachaRequest:
      properties:
        isTenDraw:
          default: false
          description: 10連ガチャかどうか
          type: boolean
      required:
      - isTenDraw
      type: object
    pack:
      example:
        cards:
        - retreatCost: 1
          masterCardId: masterCardId
          cardType: monster
          hp: 60
          evolvesTo:
          - kizuku
          - kizuku
          isEx: false
          evolvesFrom:
          - kizuku
          - kizuku
          expansion: expansion
          skills:
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          weakness: null
          imageUrl: imageUrl
          name: name
          subType: basic
          ability:
            name: name
            text: text
          rarity: 0
          element: "null"
        - retreatCost: 1
          masterCardId: masterCardId
          cardType: monster
          hp: 60
          evolvesTo:
          - kizuku
          - kizuku
          isEx: false
          evolvesFrom:
          - kizuku
          - kizuku
          expansion: expansion
          skills:
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          weakness: null
          imageUrl: imageUrl
          name: name
          subType: basic
          ability:
            name: name
            text: text
          rarity: 0
          element: "null"
      properties:
        cards:
          items:
            $ref: '#/components/schemas/masterCard'
          type: array
      required:
      - gachaPower
      - id
      - imageUrl
      - name
      - price
      type: object
    item:
      example:
        imageUrl: imageUrl
        name: name
        count: 0
        id: id
      properties:
        id:
          description: アイテムID（アイテムごとに一意）
          type: string
        name:
          description: アイテム名
          type: string
        count:
          description: 所持数
          type: integer
        imageUrl:
          description: 画像URL
          type: string
      required:
      - count
      - id
      - imageUrl
      - name
      type: object
    deckBaseWithId:
      allOf:
      - $ref: '#/components/schemas/deckBase'
      - properties:
          id:
            description: デッキID
            readOnly: true
            type: string
        required:
        - id
        type: object
      example:
        color: "null"
        name: name
        id: id
        thumbnailCard:
          id: id
    deckBase:
      description: デッキ
      properties:
        id:
          description: デッキID
          readOnly: true
          type: string
        name:
          description: デッキ名
          type: string
        thumbnailCard:
          $ref: '#/components/schemas/card'
        color:
          $ref: '#/components/schemas/element'
      required:
      - color
      - name
      - thumbnailCard
      type: object
    deckWithId:
      allOf:
      - $ref: '#/components/schemas/deck'
      - properties:
          id:
            description: デッキID
            readOnly: true
            type: string
        required:
        - id
        type: object
      example:
        energies:
        - null
        - null
        cards:
        - id: id
        - id: id
        color: "null"
        name: name
        id: id
        thumbnailCard:
          id: id
    deck:
      allOf:
      - $ref: '#/components/schemas/deckBase'
      - properties:
          cards:
            items:
              $ref: '#/components/schemas/card'
            type: array
          energies:
            items:
              $ref: '#/components/schemas/element'
            type: array
        required:
        - cards
        - energies
        - name
        type: object
    updateDeck:
      description: デッキ更新リクエスト
      properties:
        name:
          description: デッキ名
          type: string
        masterCardIds:
          description: マスターカードID
          items:
            type: string
          type: array
        thumbnailCardId:
          description: サムネイルカードID
          type: string
        energies:
          items:
            $ref: '#/components/schemas/element'
          type: array
        color:
          $ref: '#/components/schemas/element'
      required:
      - color
      - energies
      - masterCardIds
      - name
      - thumbnailCardId
      type: object
    myCardList:
      items:
        $ref: '#/components/schemas/masterCardWithCount'
      type: array
    masterCardWithCount:
      example:
        count: 0
        masterCard:
          retreatCost: 1
          masterCardId: masterCardId
          cardType: monster
          hp: 60
          evolvesTo:
          - kizuku
          - kizuku
          isEx: false
          evolvesFrom:
          - kizuku
          - kizuku
          expansion: expansion
          skills:
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          - damage: 6
            cost:
            - null
            - null
            name: name
            damageOption: x
            text: text
          weakness: null
          imageUrl: imageUrl
          name: name
          subType: basic
          ability:
            name: name
            text: text
          rarity: 0
          element: "null"
      properties:
        masterCard:
          $ref: '#/components/schemas/masterCard'
        count:
          description: カード枚数
          type: integer
      required:
      - count
      - masterCard
      type: object
    masterCard:
      oneOf:
      - $ref: '#/components/schemas/masterMonsterCard'
      - $ref: '#/components/schemas/masterSupporterCard'
      - $ref: '#/components/schemas/masterGoodsCard'
    masterMonsterCard:
      allOf:
      - $ref: '#/components/schemas/masterCardBase'
      - description: モンスターカードのプロパティ
        properties:
          hp:
            description: HP
            example: 60
            type: integer
          element:
            $ref: '#/components/schemas/element'
          weakness:
            $ref: '#/components/schemas/element'
          skills:
            description: ワザ
            items:
              $ref: '#/components/schemas/skill'
            type: array
          ability:
            $ref: '#/components/schemas/ability'
          retreatCost:
            description: 逃げるコスト
            example: 1
            type: integer
          evolvesFrom:
            description: 進化元
            items:
              example: kizuku
              type: string
            type: array
          evolvesTo:
            description: 進化先
            items:
              example: kizuku
              type: string
            type: array
          isEx:
            description: EXカードかどうか
            example: false
            type: boolean
          subType:
            enum:
            - basic
            - stage1
            - stage2
            type: string
        required:
        - element
        - hp
        - rarity
        - skills
        - weakness
        type: object
      example:
        retreatCost: 1
        masterCardId: masterCardId
        cardType: monster
        hp: 60
        evolvesTo:
        - kizuku
        - kizuku
        isEx: false
        evolvesFrom:
        - kizuku
        - kizuku
        expansion: expansion
        skills:
        - damage: 6
          cost:
          - null
          - null
          name: name
          damageOption: x
          text: text
        - damage: 6
          cost:
          - null
          - null
          name: name
          damageOption: x
          text: text
        weakness: null
        imageUrl: imageUrl
        name: name
        subType: basic
        ability:
          name: name
          text: text
        rarity: 0
        element: "null"
    masterCardBase:
      description: 全カード共通のプロパティ
      properties:
        masterCardId:
          description: カードID
          readOnly: true
          type: string
        name:
          description: カード名
          type: string
        cardType:
          $ref: '#/components/schemas/masterCardType'
        rarity:
          description: レアリティ
          type: integer
        imageUrl:
          description: カード画像URL
          type: string
        expansion:
          description: カードセット名
          type: string
      required:
      - cardType
      - imageUrl
      - masterCardId
      - name
      type: object
    masterCardType:
      enum:
      - monster
      - supporter
      - goods
      type: string
    element:
      enum:
      - "null"
      - money
      - knowledge
      - muscle
      - alchohol
      - popularity
      type: string
    skill:
      description: ワザ
      example:
        damage: 6
        cost:
        - null
        - null
        name: name
        damageOption: x
        text: text
      properties:
        name:
          description: ワザ名
          type: string
        text:
          description: 説明文
          type: string
        damage:
          description: ダメージ
          type: integer
        damageOption:
          description: x or +
          enum:
          - x
          - "+"
          type: string
        cost:
          description: コスト
          items:
            $ref: '#/components/schemas/element'
          type: array
      required:
      - cost
      - damage
      - name
      - text
      type: object
    ability:
      description: 特性
      example:
        name: name
        text: text
      properties:
        name:
          description: 特性名
          type: string
        text:
          description: 説明文
          type: string
      required:
      - name
      - text
      type: object
    masterSupporterCard:
      allOf:
      - $ref: '#/components/schemas/masterCardBase'
      - description: サポーターカードのプロパティ
        properties:
          text:
            description: 説明文
            type: string
        required:
        - text
        type: object
    masterGoodsCard:
      allOf:
      - $ref: '#/components/schemas/masterCardBase'
      - description: グッズカードのプロパティ
        properties:
          text:
            description: 説明文
            type: string
        required:
        - text
        type: object
    present:
      example:
        item:
          imageUrl: imageUrl
          name: name
          id: id
        id: id
        message: message
        itemCount: 0
      properties:
        id:
          description: プレゼントID
          type: string
        message:
          description: メッセージ
          type: string
        itemCount:
          description: アイテム数
          type: integer
        item:
          $ref: '#/components/schemas/itemBase'
      required:
      - id
      - item
      - itemCount
      - message
      type: object
    card:
      allOf:
      - $ref: '#/components/schemas/masterCard'
      - properties:
          id:
            description: カードID
            readOnly: true
            type: string
        required:
        - id
        type: object
      example:
        id: id
    itemBase:
      example:
        imageUrl: imageUrl
        name: name
        id: id
      properties:
        id:
          description: アイテムID（アイテムごとに一意）
          type: string
        name:
          description: アイテム名
          type: string
        imageUrl:
          description: 画像URL
          type: string
      required:
      - id
      - imageUrl
      - name
      type: object
    createNewDeck_201_response:
      example:
        id: id
      properties:
        id:
          description: デッキID
          type: string
      required:
      - id
      type: object
